---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Fedora)
    tags: always
    package:
      update_cache: yes
      state: latest
    when: ansible_distribution == "Fedora"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: false
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: Ensure Homebrew is installed
    command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    args:
      creates: /opt/homebrew/bin/brew

  - name: Install Terraform via Homebrew
    homebrew:
      name: terraform
      state: present

- hosts: web_servers
  become: true
  tasks:

  - name: Update distro repo index and install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: install apache and php for Fedora servers
    tags: apache,httpd,Fedora
    package:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

  - name: start httpd (Fedora)
    tags: apache,Fedora,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Fedora"
    register: httpd

  - name: restart httpd (Fedora)
    tags: apache,Fedora,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: change e-mail address for admin
    tags: apache,Fedora,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "Fedora"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  
  - name: Disable and stop firewalld (Fedora)
    service:
      name: firewalld
      state: stopped
      enabled: no
    when: ansible_distribution == "Fedora"

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package (Fedora)
    tags: Fedora,db,mariadb
    package:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"
  
  - name: install mariadb package (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
  
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
